// src/App.tsx
import React from 'react';
import './App.css';

declare function mainScript(): void;


class App3 extends React.Component<any, any> {
    render() {
        return (
            <span>test2</span>
        );
    }

    asd() {
        console.log('asd');
    }
}

class App2 extends React.Component<any, any> {


    render() {
        console.log(this.props.children);
        // React.Children.forEach(this.props, function(child) {
        //     console.log(child.type.DisplayName);
        // });

        return (
            <span>test1</span>
        );
    }
}

class App extends React.Component<any, any> {
    render() {
        return (
            <>
                <header className="site-header">
                    <div className="container">
                        <div className="row">
                            <div className="col-xs-12">

                                <a href="../index.html" className="site-header__logo">Taleh Ibrahimi</a>


                                <ul className="site-header__nav hidden-xs">

                                    <li><a href="/blue/">About Me</a></li>

                                    <li><a href="/blue/manage-content">Portfolio</a></li>

                                    <li><a href="/blue/404">Blog</a></li>

                                    <li><a href="/blue/404">Contact</a></li>

                                </ul>
                                <button className="offcanvas-toggle visible-xs">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                </button>

                            </div>

                        </div>

                    </div>

                </header>

                <div className="hero-subheader">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-7">
                                <div className="align-container" data-mh>
                                    <div className="align-inner">

                                        <h1 className="hero-subheader__title">Getting Started</h1>


                                        <p className="hero-subheader__desc">In this section you'll find basic information about Doks and how
                                            to
                                            install
                                            it and use it properly. If you're first time user then you should read Getting Started section
                                            first.</p>


                                        <a href="../configuration/index.html" className="btn btn--dark btn--rounded btn--w-icon">
                                            <i className="icon icon--arrow-right"></i>
                                            Configuration
                                        </a>


                                    </div>

                                </div>

                            </div>


                        </div>

                    </div>

                </div>

                <div className="section">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-7">
                                <div className="content">
                                    <h2 id="what-is-doks">What is Doks?</h2>
                                    <p>Doks is <a href="https://jekyllrb.com/">Jekyll</a> theme created for project documentations.<br/>
                                        You can use it with <a href="https://pages.github.com/">GitHub</a> and <a
                                            href="https://about.gitlab.com/features/pages/">GitLab Pages</a> as well as a standalone
                                        project.
                                    </p>

                                    <h2 id="what-is-jekyll">What is Jekyll?</h2>
                                    <p><a href="https://jekyllrb.com/">Jekyll</a> is a simple, blog-aware, static site generator. It takes a
                                        template directory containing raw text files in various formats, runs it through a converter
                                        (like <a
                                            href="https://daringfireball.net/projects/markdown/">Markdown</a>) and <a
                                            href="https://github.com/Shopify/liquid/wiki">Liquid</a> renderer, and spits out a complete,
                                        ready-to-publish static website suitable for serving with your favourite web server.</p>

                                    <div className="callout callout--info">
                                        <p><strong>Full Jekyll documentation</strong> You can find full Jekyll documentation <a
                                            href="https://jekyllrb.com/docs/home/" target="blank">here</a>.</p>
                                    </div>

                                    <h2 id="install-jekyll">Install Jekyll</h2>
                                    <h3 id="requirements">Requirements</h3>
                                    <p>Installing Jekyll should be straight-forward if all requirements are met. Before you start, make sure
                                        your
                                        system has the following:</p>

                                    <ul>
                                        <li>GNU/Linux, Unix, or macOS</li>
                                        <li><a href="https://www.ruby-lang.org/en/downloads/">Ruby</a> version 2.0 or above, including all
                                            development headers
                                        </li>
                                        <li><a href="https://rubygems.org/pages/download">RubyGems</a></li>
                                        <li><a href="https://gcc.gnu.org/install/">GCC</a> and <a
                                            href="https://www.gnu.org/software/make/">Make</a>
                                            (in case your system doesn’t have them installed, which you can check by running <code
                                                className="highlighter-rouge">gcc -v</code> and <code className="highlighter-rouge">make
                                                -v</code> in your
                                            system’s command line interface)
                                        </li>
                                    </ul>

                                    <h3 id="install-with-rubygems">Install with RubyGems</h3>
                                    <p>The best way to install Jekyll is via <a href="https://rubygems.org/pages/download">RubyGems</a>. At
                                        the
                                        terminal prompt, simply run the following command to install Jekyll:</p>

                                    <div className="language-sh highlighter-rouge">
                                        <div className="highlight"><pre className="highlight"><code><span className="nv">$ </span>gem install jekyll
</code></pre>
                                        </div>
                                    </div>

                                    <p>All of Jekyll’s gem dependencies are automatically installed by the above command, so you won’t have
                                        to
                                        worry about them at all.</p>

                                    <div className="callout callout--info">
                                        <p><strong>Full Jekyll installation guide</strong> You can find full Jekyll installation guide <a
                                            href="https://jekyllrb.com/docs/installation/" target="blank">here</a>.</p>
                                    </div>

                                    <h2 id="install-doks">Install Doks</h2>
                                    <h3 id="download">Download</h3>
                                    <p>Download your Doks theme from ThemeForest (you should get <code
                                        className="highlighter-rouge">doks.zip</code>)
                                        and unzip it.</p>

                                    <h3 id="start-development-server">Start development server</h3>
                                    <p>Jekyll comes with a built-in development server that will allow you to preview what the generated
                                        site
                                        will
                                        look like in your browser locally.</p>

                                    <p>You can run this commands inside theme folder:</p>

                                    <div className="language-sh highlighter-rouge">
                                        <div className="highlight"><pre className="highlight"><code><span className="nv">$ </span>jekyll serve
<span className="c"># A development server will run at http://localhost:4000/</span>
<span className="c"># Auto-regeneration: enabled. Use `--no-watch` to disable.</span>

<span className="nv">$ </span>jekyll serve <span className="nt">--no-watch</span>
<span className="c"># Same as `jekyll serve` but will not watch for changes.</span>

<span className="nv">$ </span>jekyll serve <span className="nt">--detach</span>
<span className="c"># Same as `jekyll serve` but will detach from the current terminal.</span>
<span className="c"># If you need to kill the server, you can `kill -9 1234` where "1234" is the PID.</span>
<span className="c"># If you cannot find the PID, then do, `ps aux | grep jekyll` and kill the instance.</span>
</code></pre>
                                        </div>
                                    </div>

                                    <h2 id="directory-structure">Directory structure</h2>
                                    <p>This is Doks basic directory structure which looks like this:</p>

                                    <div className="language-sh highlighter-rouge">
                                        <div className="highlight"><pre className="highlight"><code>doks/
├── doks-theme/ <span className="c"># Doks theme source files.</span>
├── _config.yml <span className="c"># Stores Jekyll configuration data.</span>
├── .eslintrc <span className="c"># ESlint configuration file.</span>
├── .gitignore <span className="c"># Git related file which specifies intentionally untracked files to ignore.</span>
├── .gitlab-ci.yml <span className="c"># File used by GitLab Runner to manage your project's jobs.</span>
├── .htaccess <span className="c"># Configuration file for use on web servers running the Apache Web Server software.</span>
├── 404.md <span className="c"># Error 404 layout markdown template.</span>
├── default.md <span className="c"># Default layout markdown template.</span>
├── favicon.ico <span className="c"># Favicon icon.</span>
└── index.md <span className="c"># Homepage layout markdown template.</span>
</code></pre>
                                        </div>
                                    </div>

                                    <h2 id="icons">Icons</h2>
                                    <p>List of icons you can use in some places such as social list in footer or buttons in homepage
                                        layout.</p>

                                    <h2 id="change-log">Change Log</h2>
                                    <p>All notable changes to this project will be documented here.
                                        This project adheres to <a href="http://semver.org/">Semantic Versioning</a>.</p>

                                    <h3 id="v100---2017-12-08">[v1.0.0] - 2017-12-08</h3>
                                    <p>Initial release.</p>

                                    <h2 id="credits">Credits</h2>
                                    <p>List of vendor assets we used to create this theme:</p>
                                    <ul>
                                        <li><a href="https://github.com/twbs/bootstrap">Bootstrap</a> (<a
                                            href="https://github.com/twbs/bootstrap/blob/master/LICENSE">MIT License</a>)
                                        </li>
                                        <li><a href="https://github.com/necolas/normalize.css">normalize.css</a> (<a
                                            href="https://github.com/necolas/normalize.css/blob/master/LICENSE.md">MIT License</a>)
                                        </li>
                                        <li><a href="http://jquery.com">jQuery</a> (<a href="https://tldrlegal.com/license/mit-license">MIT
                                            License</a>)
                                        </li>
                                        <li><a href="https://github.com/liabru/jquery-match-height">jquery-match-height</a> (<a
                                            href="https://github.com/liabru/jquery-match-height/blob/master/LICENSE">MIT License</a>)
                                        </li>
                                        <li><a href="https://github.com/simple-icons/simple-icons">simple-icons</a> (<a
                                            href="https://github.com/simple-icons/simple-icons/blob/develop/LICENSE.md">CC0-1.0 License</a>)
                                        </li>
                                        <li><a href="https://github.com/colebemis/feather">feather</a> (<a
                                            href="https://github.com/colebemis/feather/blob/master/LICENSE">MIT License</a>)
                                        </li>
                                        <li><a href="https://fonts.google.com/specimen/Montserrat">Montserrat</a> (<a
                                            href="http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&amp;id=OFL">SIL Open Font
                                            License,
                                            1.1</a>)
                                        </li>
                                        <li><a href="https://fonts.google.com/specimen/Noto+Sans">Noto Sans</a> (<a
                                            href="http://www.apache.org/licenses/LICENSE-2.0.html">Apache License, version 2.0</a>)
                                        </li>
                                        <li><a href="https://fonts.google.com/specimen/Source+Code+Pro">Source Code Pro</a> (<a
                                            href="http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&amp;id=OFL">SIL Open Font
                                            License,
                                            1.1</a>)
                                        </li>
                                    </ul>

                                </div>

                            </div>

                            <div className="col-md-4 col-md-offset-1">
                                <div className="sections-list-wrapper">
                                    <div className="sections-list js-sections js-affix js-scrollspy hidden-xs hidden-sm"></div>

                                </div>
                            </div>

                        </div>

                    </div>

                </div>

                <div className="js-footer-area">

                    <nav className="page-nav">
                        <div className="container">
                            <div className="row">
                                <div className="col-xs-12">


                                    <a href="../configuration/index.html" className="page-nav__item page-nav__item--next">
                                        Configuration
                                        <i className="icon icon--arrow-right"></i>
                                    </a>

                                </div>

                            </div>

                        </div>

                    </nav>


                    <div className="micro-nav">
                        <div className="container">
                            <div className="row">
                                <div className="col-xs-12">
                                    <a href="../index.html" className="micro-nav__back">
                                        <i className="icon icon--arrow-left"></i>
                                        Back to homepage
                                    </a>
                                </div>

                            </div>

                        </div>

                    </div>


                    <footer className="site-footer">
                        <div className="container">
                            <div className="row">
                                <div className="col-sm-6">

                                    <a href="../index.html" className="site-footer__logo">Doks</a>
                                    <hr/>
                                    <p className="site-footer__copyright">Copyright &copy; 2017. - Themejack <br/>All rights reserved.</p>
                                </div>


                                <div className="col-sm-6 align-right">
                                    <ul className="social-list">

                                        <li>
                                            <a href="https://twitter.com/themejack" target="_blank"
                                               className="social-list__item social-list__item--twitter">
                                                <i className="icon icon--twitter"></i>
                                            </a>
                                        </li>

                                        <li>
                                            <a href="https://github.com/themejack" target="_blank"
                                               className="social-list__item social-list__item--github">
                                                <i className="icon icon--github"></i>
                                            </a>
                                        </li>

                                    </ul>

                                </div>


                            </div>

                        </div>

                    </footer>


                </div>
            </>
        );
    }

    componentDidMount() {
        mainScript();
    }
}

export default App;

// src/app/app.component.ts
import {AfterContentInit, Component} from '@angular/core';
import {Router} from '@angular/router';

import * as test1 from 'raw-loader!./blog/test1.html';

console.log(test1);

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements AfterContentInit {
  title = 'talehibrahimlicom';

  constructor(private router: Router) {
    const path = localStorage.getItem('path');

    if (path) {
      localStorage.removeItem('path');
      this.router.navigate([path]);
    }
  }

  ngAfterContentInit(): void {
    window['matchHeiht']();
    window['mainScript']();
  }


}

<div class="offcanvas visible-xs">
  <ul class="offcanvas__nav">

    <li><a href="/blue/">Homepage</a></li>

    <li><a href="/blue/manage-content">Content Page</a></li>

    <li><a href="/blue/404">404 Page</a></li>

  </ul><!-- /.offcanvas__nav -->
</div><!-- /.offcanvas -->


<header class="site-header">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">

        <a href="/blue/" class="site-header__logo">Taleh Ibrahimli</a>


        <ul class="site-header__nav hidden-xs">

          <li><a href="/blue/">About Me</a></li>

          <li><a href="/blue/manage-content">Portfolio</a></li>

          <li><a href="/blue/404">Contact</a></li>

        </ul><!-- /.site-header__nav -->
        <button class="offcanvas-toggle visible-xs">
          <span></span>
          <span></span>
          <span></span>
        </button><!-- /.offcanvas-toggle -->

      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</header><!-- /.site-header -->


<div class="hero-subheader">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <div class="align-container" data-mh>
          <div class="align-inner">

            <h1 class="hero-subheader__title">Java Software Architect</h1>


            <p class="hero-subheader__desc">We've prepared special guide for content management. Let's learn how to add
              syntax highlighting, examples, callouts and much more.</p>


          </div><!-- /.align-inner -->
        </div><!-- /.align-container -->
      </div><!-- /.col -->

    </div><!-- /.row -->
  </div><!-- /.container -->
</div><!-- /.hero-subheader -->
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <div class="content">
          <h2 id="add-content">Add content</h2>
          <p>Content should be in <a href="https://daringfireball.net/projects/markdown/">Markdown</a> format and you
            shouldn’t remove <code class="highlighter-rouge">.yml</code> comments on top of the <code
              class="highlighter-rouge">.md</code> files, errors may occur if you remove them.</p>

          <h3 id="homepage">Homepage</h3>
          <p>In main <code class="highlighter-rouge">index.md</code> file you add your homepage documentation content.
            Don’t forget to setup variables on top of the file. We’ve already added all variables, all you have to do is
            to update them.</p>

          <h3 id="pages">Pages</h3>
          <p>To add new pages just create new <code class="highlighter-rouge">.md</code> file with proper <code
            class="highlighter-rouge">.yml</code> comments on top of the file. Pages use <code
            class="highlighter-rouge">default</code> layout template. Basic example of <code class="highlighter-rouge">default</code>
            layout template can be found in <code class="highlighter-rouge">default.md</code>.</p>

          <h3 id="404-error-page">404 error page</h3>
          <p>Doks have custom 404 error page template. You can edit its content in <code class="highlighter-rouge">404.md</code>.
            If you’re hosting your site on Apache Web Servers, we’ve already added custom <code
              class="highlighter-rouge">.htaccess</code> file to update path to your 404 error page.</p>

          <div class="callout callout--info">
            <p><strong>Full 404 error page setup guide.</strong> You can find full 404 error page setup guide <a
              href="https://jekyllrb.com/tutorials/custom-404-page/">here</a>.</p>
          </div>

          <h2 id="external-and-internal-links">External and internal links</h2>
          <p>All links on your website should link to internal pages. <br/>
            There’s few exception to this rule:</p>

          <ul>
            <li>In content you can use an external links.</li>
            <li>On homepage header buttons you can use an external links but you have to set <code
              class="highlighter-rouge">external_url</code> to <code class="highlighter-rouge">true</code>. Same applies
              to author box on default and homepage layouts.
            </li>
            <li>In footer social list you <strong>have</strong> to use an external links.</li>
          </ul>

          <h2 id="relative-urls">Relative URLs</h2>
          <p>If you link internal pages in your content you have to add <code class="highlighter-rouge">baseurl</code>
            prefix to your links. This applies only to sites which will not be deployed in <code
              class="highlighter-rouge">root</code> directory of your server.</p>

          <div class="callout callout--info">
            <p><strong>Relative URLs configuration.</strong> In "Configuration" section you can read more about relative
              URLs configuration.</p>
          </div>

          <h2 id="syntax-highlighting">Syntax Highlighting</h2>
          <p>You can call out code or a command within a sentence with single backticks. The text within the backticks
            will not be formatted.<br/>
            To format code or text into its own distinct block, use triple backticks.<br/>
            Best <a
              href="https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code">example</a> of
            this can be found <a
              href="https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code">here</a>.</p>

          <p>Furthermore, you can add an optional language identifier to enable syntax highlighting in your fenced code
            block. Best <a
              href="https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting">example</a>
            of this can be found <a
              href="https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting">here</a>.
          </p>

          <h2 id="examples">Examples</h2>
          <p>To add example bar add following <code class="highlighter-rouge">html</code> above your code block.</p>

          <div class="example"></div>
          <div class="language-html highlighter-rouge">
            <div class="highlight"><pre class="highlight"><code><span class="nt">&lt;div</span> <span
              class="na">class=</span><span class="s">"example"</span><span class="nt">&gt;</span>
    <span class="nt">&lt;a</span> <span class="na">href=</span><span class="s">"#"</span> <span
                class="na">target=</span><span class="s">"blank"</span><span class="nt">&gt;</span>Preview<span
                class="nt">&lt;/a&gt;</span>
<span class="nt">&lt;/div&gt;</span>
</code></pre>
            </div>
          </div>

          <h2 id="callouts">Callouts</h2>
          <p>To add callout to your documentation simply add following <code class="highlighter-rouge">html</code> code.<br/>
            Choose between few variations:</p>

          <ul>
            <li>Info: <code class="highlighter-rouge">callout--info</code></li>
            <li>Warning: <code class="highlighter-rouge">callout--warning</code></li>
            <li>Danger: <code class="highlighter-rouge">callout--danger</code></li>
            <li>Success: <code class="highlighter-rouge">callout--success</code></li>
          </ul>

          <div class="example"></div>
          <div class="language-html highlighter-rouge">
            <div class="highlight"><pre class="highlight"><code><span class="nt">&lt;div</span> <span
              class="na">class=</span><span class="s">"callout callout--info"</span><span class="nt">&gt;</span>
    <span class="nt">&lt;p&gt;&lt;strong&gt;</span>Lorem ipsum dolor sit amet!<span class="nt">&lt;/strong&gt;</span> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<span
                class="nt">&lt;/p&gt;</span>
    <span class="nt">&lt;p&gt;</span>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<span
                class="nt">&lt;/p&gt;</span>
<span class="nt">&lt;/div&gt;</span>

<span class="nt">&lt;div</span> <span class="na">class=</span><span class="s">"callout callout--warning"</span><span
                class="nt">&gt;</span>
    <span class="nt">&lt;p&gt;&lt;strong&gt;</span>Lorem ipsum dolor sit amet!<span class="nt">&lt;/strong&gt;</span> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<span
                class="nt">&lt;/p&gt;</span>
    <span class="nt">&lt;p&gt;</span>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<span
                class="nt">&lt;/p&gt;</span>
<span class="nt">&lt;/div&gt;</span>

<span class="nt">&lt;div</span> <span class="na">class=</span><span class="s">"callout callout--danger"</span><span
                class="nt">&gt;</span>
    <span class="nt">&lt;p&gt;&lt;strong&gt;</span>Lorem ipsum dolor sit amet!<span class="nt">&lt;/strong&gt;</span> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<span
                class="nt">&lt;/p&gt;</span>
    <span class="nt">&lt;p&gt;</span>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<span
                class="nt">&lt;/p&gt;</span>
<span class="nt">&lt;/div&gt;</span>

<span class="nt">&lt;div</span> <span class="na">class=</span><span class="s">"callout callout--success"</span><span
                class="nt">&gt;</span>
    <span class="nt">&lt;p&gt;&lt;strong&gt;</span>Lorem ipsum dolor sit amet!<span class="nt">&lt;/strong&gt;</span> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<span
                class="nt">&lt;/p&gt;</span>
    <span class="nt">&lt;p&gt;</span>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.<span
                class="nt">&lt;/p&gt;</span>
<span class="nt">&lt;/div&gt;</span>
</code></pre>
            </div>
          </div>

          <div class="callout callout--info">
            <p><strong>Lorem ipsum dolor sit amet!</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit,
              sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
              dolore magna aliqua.</p>
          </div>

          <div class="callout callout--warning">
            <p><strong>Lorem ipsum dolor sit amet!</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit,
              sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
              dolore magna aliqua.</p>
          </div>

          <div class="callout callout--danger">
            <p><strong>Lorem ipsum dolor sit amet!</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit,
              sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
              dolore magna aliqua.</p>
          </div>

          <div class="callout callout--success">
            <p><strong>Lorem ipsum dolor sit amet!</strong> Lorem ipsum dolor sit amet, consectetur adipisicing elit,
              sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
              dolore magna aliqua.</p>
          </div>

        </div><!-- /.content -->
      </div><!-- /.col -->
      <div class="col-md-4 col-md-offset-1">
        <div class="sections-list-wrapper">
          <div class="sections-list js-sections js-affix js-scrollspy hidden-xs hidden-sm"></div>
          <!-- /.sections-list -->
        </div>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container -->
</div><!-- /.section -->

<div class="js-footer-area">
  <footer class="site-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">

          <a href="../index.html" class="site-footer__logo">Taleh Ibrahimli</a>


          <hr>
          <p class="site-footer__copyright">Copyright &copy; 2020. - Personal Website <br>All rights reserved.</p>

        </div><!-- /.col -->

        <div class="col-sm-6 align-right">
          <ul class="social-list">

            <li>
              <a href="https://twitter.com/themejack" target="_blank"
                 class="social-list__item social-list__item--twitter">
                <i class="icon icon--twitter"></i>
              </a>
            </li>

            <li>
              <a href="https://github.com/themejack" target="_blank"
                 class="social-list__item social-list__item--github">
                <i class="icon icon--github"></i>
              </a>
            </li>

          </ul><!-- /.social-list -->
        </div><!-- /.col -->

      </div><!-- /.row -->
    </div><!-- /.container -->
  </footer><!-- /.site-footer -->

</div><!-- /.js-footer-area -->
